name: Build and Check
on:
  push:
    tags:
      - "v*"
jobs:

  build-and-deploy:
    runs-on: macos-latest
    steps:        
      
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Use Node.js 13.x
        uses: actions/setup-node@master
        with:
          node-version: 13.x
      
      - name: Install
        run: |
             npm install -g yarn && npm install -g @zeit/ncc
             
      - name: Build and check
        run: |
             yarn install && yarn build && yarn test
