name: Build and Deploy
on:
  push:
    tags:
      - "v*"
jobs:

  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:        
      
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Use Node.js 8.x
        uses: actions/setup-node@master
        with:
          node-version: 8.x
      
      - name: Install
        run: |
             npm install -g yarn
             
      - name: Build and deploy
        run: |
             yarn install && yarn build
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false        
